export class Users {
  public UserId: number;
  public Email: string;
  public IsEmailConfirmed: boolean;
  public Name: string;
  public FirstName: string;
  public LastName: string;
  public UserName: string;
  public Password: string;
  public ConfirmPassword: string;
  public PhoneNumber: number;
  public IsPhoneNumberVerified: boolean;
  public AccessFailedCount: number;
  public IsLocked: boolean;
  public IsTwoFactorEnabled: boolean;
  public TwoFactorCode: string;
  public TwoFactorExpiryTime: Date;
  public TwoFactorType: number;
  public RoleId: number;
  public IsActive: boolean;
  public CellNumber: number;
  public CostPerHour: number;
  public Skills: string;
  public GroupId: number;
  public UserTheme: string;
  public OfficeToken: string;
  public EmployeeTypeId: number;
  public CountryId: number;
  public UpdatedOn: Date;
  public UpdatedBy: string;
  public UpdatedById: number;
  public CreatedOn: Date;
  public CreatedBy: string;
  public CreatedById: number;
  public Commission: number;
  public Address: string;
  public City: string;
  public State: string;
  public ZipCode: string;
  public StateId: number;
  public Country: string;
  public CityId: number;
  public IsSales: boolean;
  public IsAdmin: boolean;
  public QuoteToggle: boolean = false;
  public AboutMe: string;
  public EmailSignature: string;
  public AdminPassword: string;
  public ConfirmAdminPassword: string;
  public ImageUrl: string;
  public GmailUserName: string;
  public GmailPassword: string;
  public Signature: string;
  public HashData: string;
}

export class UserCost {
  public Id: number;
  public IsPerHour: boolean;
  public PerHourCost: number;
  public IsPerMonth: boolean;
  public PerMonthCost: number;
  public PerMonthTotalHours: number;
  public IsPerLead: boolean;
  public PerLeadCost: number;
  public IsPerPaidInvoice: boolean;
  public PerPaidInvoiceCost: number;
  public IsFullTime: boolean;
  public FullTimeCost: number;
  public FullTimeHours: number;
  public IsPartTime: boolean;
  public PartTimeCost: number;
  public PartTimeHours: number;
  public UserId: number;
  public UpdatedOn: Date;
  public UpdatedBy: string;
  public UpdatedById: number;
  public CreatedOn: Date;
  public CreatedBy: string;
  public CreatedById: number;
  public VendorId: number;
  public PartnerId: number;
  public ReferralId: number;
  public UserCostDropdownId: number;
}
export class UserCostDropdown {
  public Id: number;
  public Name: string;
}
export class UserGoal {
  public Id: number;
  public AvarageSalePrice: number;
  public MinimalGoalAmount: number;
  public GoodRevenueGoalAmount: number;
  public GreatRevenueGoalAmount: number;
  public MinimalGoalLead: number;
  public GoodRevenueGoalLead: number;
  public GreatRevenueGoalLead: number;
  public UserId: number;
  public ClosingRatioInterval: number;
}
