# Stage 1
#FROM node:16-alpine as build-step
#RUN mkdir -p /app
#WORKDIR /app
#COPY [".", "./"]
#COPY ./package.json /app
#RUN npm install
#COPY . /app
#RUN npm run build --prod
#RUN npm install --save-dev @angular-devkit/build-angular
## Stage 2
#FROM  BASE_IMAGE:VERSION
#CMD ["/bin/bash"]
FROM arm64v8/nginx:1.20.1-alpine
#FROM nginx:1.20.1-alpine
#RUN echo "hello"
COPY /dist/k9crm-company-app /usr/share/nginx/html
COPY /src/nginx-custom.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
EXPOSE 443
#ENTRYPOINT ["entry.sh"]
