import { NgModule } from '@angular/core';
import { Routes, RouterModule, ɵEmptyOutletComponent } from '@angular/router';
import { AuthGuardService } from './helper/AuthGuard';
import { NavPermissionGuardService } from './helper/NavPermissionGuard';
import { MsalGuard } from '@azure/msal-angular';

const routes: Routes = [
  //{ path: '', loadChildren: () => import('./home/home.module').then(m => m.HomeModule), canActivate: [NavPermissionGuardService], data: { permission: "1" } },
  { path: 'empty', outlet: "modal", component: ɵEmptyOutletComponent },
  { path: 'home', loadChildren: () => import('./home/home.module').then(m => m.HomeModule), canActivate: [NavPermissionGuardService] },
  //{ path: 'login', loadChildren: () => import('./login/login.module').then(m => m.LoginModule) },
  /*{ path: '', loadChildren: () => import('./login/login.module').then(m => m.LoginModule) },*/
  //{ path: 'home', loadChildren: () => import('./login/login.module').then(m => m.LoginModule) },
  { path: 'adddeals', loadChildren: () => import('./adddeals/adddeals.module').then(m => m.AdddealsModule), canActivate: [MsalGuard] },
  { path: 'adddealsmodal', loadChildren: () => import('./adddeals/adddeals.module').then(m => m.AdddealsModule), canActivate: [MsalGuard], outlet: "modal" },
  { path: 'addvendorsmodal', loadChildren: () => import('./addvendor/addvendor.module').then(m => m.AddvendorModule), canActivate: [MsalGuard], outlet: "modal" },
  { path: 'listdeals', loadChildren: () => import('./listdeals/listdeals.module').then(m => m.ListdealsModule), canActivate: [MsalGuard] },
  { path: 'listleads', loadChildren: () => import('./listleads/listleads.module').then(m => m.ListleadsModule), canActivate: [MsalGuard] },
  { path: 'addleads', loadChildren: () => import('./addleads/addleads.module').then(m => m.AddleadsModule), canActivate: [MsalGuard] },
  { path: 'addleadsmodal', loadChildren: () => import('./addleads/addleads.module').then(m => m.AddleadsModule), canActivate: [MsalGuard], outlet: "modal" },
  { path: 'users', loadChildren: () => import('./users/users.module').then(m => m.UsersModule), canActivate: [MsalGuard] },
  { path: 'adduser', loadChildren: () => import('./adduser/adduser.module').then(m => m.AdduserModule), canActivate: [MsalGuard] },
  { path: 'edituser', loadChildren: () => import('./adduser/adduser.module').then(m => m.AdduserModule), canActivate: [MsalGuard] },
  { path: 'addusermodal', loadChildren: () => import('./adduser/adduser.module').then(m => m.AdduserModule), canActivate: [MsalGuard], outlet: "modal" },
  { path: 'manageuser', loadChildren: () => import('./manageuser/manageuser.module').then(m => m.ManageuserModule), canActivate: [MsalGuard] },
  { path: 'dashboard', loadChildren: () => import('./dashboard/dashboard.module').then(m => m.DashboardModule), canActivate: [MsalGuard] },
  { path: 'import', loadChildren: () => import('./import/import.module').then(m => m.ImportModule), canActivate: [MsalGuard] },
  { path: 'import', loadChildren: () => import('./import/import.module').then(m => m.ImportModule), canActivate: [MsalGuard] },
  { path: 'addgroup', loadChildren: () => import('./addgroup/addgroup.module').then(m => m.AddgroupModule), canActivate: [MsalGuard] },
  { path: 'pipeline/:id', loadChildren: () => import('./pipeline/pipeline.module').then(m => m.PipelineModule), canActivate: [MsalGuard] },
  { path: 'pipeline', loadChildren: () => import('./pipeline/pipeline.module').then(m => m.PipelineModule), canActivate: [MsalGuard] },
  { path: 'addorganization', loadChildren: () => import('./addorganization/addorganization.module').then(m => m.AddorganizationModule), canActivate: [MsalGuard] },
  { path: 'listorganization', loadChildren: () => import('./listorganization/listorganization.module').then(m => m.ListorganizationModule), canActivate: [MsalGuard] },
  { path: 'custom-fields', loadChildren: () => import('./custom-fields/custom-fields.module').then(m => m.CustomFieldsModule), canActivate: [MsalGuard] },
  { path: 'listcurrency', loadChildren: () => import('./listcurrency/listcurrency.module').then(m => m.ListcurrencyModule), canActivate: [MsalGuard] },
  { path: 'addcurrency', loadChildren: () => import('./addcurrency/addcurrency.module').then(m => m.AddcurrencyModule), canActivate: [MsalGuard] },
  { path: 'opportunityview', loadChildren: () => import('./opportunityview/opportunityview.module').then(m => m.OpportunityviewModule), canActivate: [MsalGuard] },
  { path: 'addvendor', loadChildren: () => import('./addvendor/addvendor.module').then(m => m.AddvendorModule), canActivate: [MsalGuard] },
  { path: 'editvendor', loadChildren: () => import('./addvendor/addvendor.module').then(m => m.AddvendorModule), canActivate: [MsalGuard] },
  { path: 'addvendormodal', loadChildren: () => import('./addvendor/addvendor.module').then(m => m.AddvendorModule), canActivate: [MsalGuard], outlet: "modal" },
  { path: 'addnetworkingmodal', loadChildren: () => import('./addnetworking/addnetworking.module').then(m => m.AddnetworkingModule), canActivate: [MsalGuard], outlet: "modal" },
  { path: 'pipelinemodal', loadChildren: () => import('./pipeline/pipeline.module').then(m => m.PipelineModule), canActivate: [MsalGuard], outlet: "modal" },
  { path: 'listvendor', loadChildren: () => import('./listvendor/listvendor.module').then(m => m.ListvendorModule), canActivate: [MsalGuard] },
  { path: 'listeventshow', loadChildren: () => import('./listeventshow/listeventshow.module').then(m => m.ListeventshowModule), canActivate: [MsalGuard] },
  { path: 'addeventshow', loadChildren: () => import('./addeventshow/addeventshow.module').then(m => m.AddeventshowModule), canActivate: [MsalGuard] },
  { path: 'editeventshow', loadChildren: () => import('./addeventshow/addeventshow.module').then(m => m.AddeventshowModule), canActivate: [MsalGuard] },
  { path: 'addeventshowmodal', loadChildren: () => import('./addeventshow/addeventshow.module').then(m => m.AddeventshowModule), canActivate: [MsalGuard], outlet: "modal" },
  { path: 'funnel', loadChildren: () => import('./agenda/agenda.module').then(m => m.AgendaModule), canActivate: [MsalGuard] },
  { path: 'todolist', loadChildren: () => import('./todolist/todolist.module').then(m => m.TodolistModule), canActivate: [MsalGuard] },
  { path: 'todo', loadChildren: () => import('./todo/todo.module').then(m => m.TodoModule), canActivate: [MsalGuard] },
  { path: 'todomodal', loadChildren: () => import('./todo/todo.module').then(m => m.TodoModule), canActivate: [MsalGuard], outlet: "modal" },
  { path: 'managerole', loadChildren: () => import('./managerole/managerole.module').then(m => m.ManageroleModule), canActivate: [MsalGuard] },
  { path: 'sfcalendar', loadChildren: () => import('./sfcalendar/sfcalendar.module').then(m => m.SfcalendarModule), canActivate: [MsalGuard] },
  { path: 'sfcalendarmodal', loadChildren: () => import('./sfcalendar/sfcalendar.module').then(m => m.SfcalendarModule), canActivate: [MsalGuard], outlet: "modal" },
  { path: 'vendorsteps', loadChildren: () => import('./vendorsteps/vendorsteps.module').then(m => m.VendorstepsModule), canActivate: [MsalGuard] },
  { path: 'editnetworking', loadChildren: () => import('./addnetworking/addnetworking.module').then(m => m.AddnetworkingModule), canActivate: [MsalGuard] },
  { path: 'addnetworking', loadChildren: () => import('./addnetworking/addnetworking.module').then(m => m.AddnetworkingModule), canActivate: [MsalGuard] },
  { path: 'listnetworking', loadChildren: () => import('./listnetworking/listnetworking.module').then(m => m.ListnetworkingModule), canActivate: [MsalGuard] },
  { path: 'settings', loadChildren: () => import('./settings/settings.module').then(m => m.SettingsModule), canActivate: [MsalGuard] },
  { path: 'companyregister', loadChildren: () => import('./companyregister/companyregister.module').then(m => m.CompanyregisterModule) },
  { path: 'securitypermissions', loadChildren: () => import('./securityPermission/securityPermission.module').then(m => m.SecurityPermissionModule), canActivate: [MsalGuard] },
  { path: 'listcompanyregister', loadChildren: () => import('./listcompanyregister/listcompanyregister.module').then(m => m.ListcompanyregisterModule), canActivate: [MsalGuard] },
  { path: 'email', loadChildren: () => import('./email/email.module').then(m => m.EmailModule), canActivate: [MsalGuard] },
  { path: 'reports', loadChildren: () => import('./reports/reports.module').then(m => m.ReportsModule), canActivate: [MsalGuard] },
  { path: 'listcontactinfo', loadChildren: () => import('./listcontactinfo/listcontactinfo.module').then(m => m.ListcontactinfoModule), canActivate: [MsalGuard] },
  { path: 'calendarselect', loadChildren: () => import('./calendarselect/calendarselect.module').then(m => m.CalendarselectModule), canActivate: [MsalGuard] },
  { path: 'steps', loadChildren: () => import('./steps/steps.module').then(m => m.StepsModule), canActivate: [MsalGuard] },
  { path: 'addpartner', loadChildren: () => import('./addpartner/addpartner.module').then(m => m.AddpartnerModule), canActivate: [MsalGuard] },
  { path: 'listpartner', loadChildren: () => import('./listpartner/listpartner.module').then(m => m.ListpartnerModule), canActivate: [MsalGuard] },
  { path: 'addreferral', loadChildren: () => import('./addreferral/addreferral.module').then(m => m.AddreferralModule), canActivate: [NavPermissionGuardService] },
  { path: 'addreferralmodal', loadChildren: () => import('./addreferral/addreferral.module').then(m => m.AddreferralModule), canActivate: [MsalGuard], outlet: "modal" },
  { path: 'addpartnermodal', loadChildren: () => import('./addpartner/addpartner.module').then(m => m.AddpartnerModule), canActivate: [MsalGuard], outlet: "modal" },
  { path: 'listreferral', loadChildren: () => import('./listreferral/listreferral.module').then(m => m.ListreferralModule), canActivate: [NavPermissionGuardService] },
  { path: 'leadsteps', loadChildren: () => import('./leadsteps/leadsteps.module').then(m => m.LeadstepsModule), canActivate: [MsalGuard] },
  { path: 'entityname', loadChildren: () => import('./entityname/entityname.module').then(m => m.EntitynameModule), canActivate: [MsalGuard] },
  { path: 'partnersteps', loadChildren: () => import('./partnersteps/partnersteps.module').then(m => m.PartnerstepsModule), canActivate: [MsalGuard] },
  { path: 'referralsteps', loadChildren: () => import('./referralsteps/referralsteps.module').then(m => m.ReferralstepsModule), canActivate: [MsalGuard] },
  { path: 'addpartcatalog', loadChildren: () => import('./addpartcatalog/addpartcatalog.module').then(m => m.AddpartcatalogModule), canActivate: [MsalGuard] },
  { path: 'listpartcatalog', loadChildren: () => import('./listpartcatalog/listpartcatalog.module').then(m => m.ListpartcatalogModule), canActivate: [MsalGuard] },
  { path: 'listquote', loadChildren: () => import('./listquote/listquote.module').then(m => m.ListquoteModule), canActivate: [MsalGuard] },
  { path: 'addquote', loadChildren: () => import('./addquote/addquote.module').then(m => m.AddquoteModule), canActivate: [MsalGuard] },
  { path: 'addquotemodal', loadChildren: () => import('./addquote/addquote.module').then(m => m.AddquoteModule), canActivate: [MsalGuard], outlet: "modal" },
  { path: 'addpartcatalogmodal', loadChildren: () => import('./addpartcatalog/addpartcatalog.module').then(m => m.AddpartcatalogModule), outlet: "modal" },
  { path: 'editquote', loadChildren: () => import('./addquote/addquote.module').then(m => m.AddquoteModule), canActivate: [MsalGuard] },
  { path: 'addleadreport', loadChildren: () => import('./addleadreport/addleadreport.module').then(m => m.AddleadreportModule), canActivate: [MsalGuard] },
  { path: 'listleadreport', loadChildren: () => import('./listleadreport/listleadreport.module').then(m => m.ListleadreportModule), canActivate: [MsalGuard] },
  { path: 'adduserreport', loadChildren: () => import('./adduserreport/adduserreport.module').then(m => m.AdduserreportModule), canActivate: [MsalGuard] },
  { path: 'adddealreport', loadChildren: () => import('./adddealreport/adddealreport.module').then(m => m.AdddealreportModule), canActivate: [MsalGuard] },
  { path: 'addvendorreport', loadChildren: () => import('./addvendorreport/addvendorreport.module').then(m => m.AddvendorreportModule), canActivate: [MsalGuard] },
  { path: 'addreferralreport', loadChildren: () => import('./addreferralreport/addreferralreport.module').then(m => m.AddreferralreportModule), canActivate: [MsalGuard] },
  { path: 'addpartnerreport', loadChildren: () => import('./addpartnerreport/addpartnerreport.module').then(m => m.AddpartnerreportModule), canActivate: [MsalGuard] },
  { path: 'addeventreport', loadChildren: () => import('./addeventreport/addeventreport.module').then(m => m.AddeventreportModule), canActivate: [MsalGuard] },
  { path: 'addnetworkreport', loadChildren: () => import('./addnetworkreport/addnetworkreport.module').then(m => m.AddnetworkreportModule), canActivate: [MsalGuard] },
  { path: 'dealgetreport', loadChildren: () => import('./dealgetreport/dealgetreport.module').then(m => m.DealgetreportModule), canActivate: [MsalGuard] },
  { path: 'dealgridreport', loadChildren: () => import('./dealgridreport/dealgridreport.module').then(m => m.DealgridreportModule), canActivate: [MsalGuard] },
  { path: 'opportunityvendorreport', loadChildren: () => import('./opportunityvendorreport/opportunityvendorreport.module').then(m => m.OpportunityvendorreportModule), canActivate: [MsalGuard] },
  { path: 'opportunitypartnerreport', loadChildren: () => import('./opportunitypartnerreport/opportunitypartnerreport.module').then(m => m.OpportunitypartnerreportModule), canActivate: [MsalGuard] },
  { path: 'opportunityreferralreport', loadChildren: () => import('./opportunityreferralreport/opportunityreferralreport.module').then(m => m.OpportunityreferralreportModule), canActivate: [MsalGuard] },
  { path: 'opportunityeventreport', loadChildren: () => import('./opportunityeventreport/opportunityeventreport.module').then(m => m.OpportunityeventreportModule), canActivate: [MsalGuard] },
  { path: 'opportunitynetworkreport', loadChildren: () => import('./opportunitynetworkreport/opportunitynetworkreport.module').then(m => m.OpportunitynetworkreportModule), canActivate: [MsalGuard] },
  { path: 'leadimport', loadChildren: () => import('./leadimport/leadimport.module').then(m => m.LeadimportModule), canActivate: [MsalGuard] },
  { path: 'vendorimport', loadChildren: () => import('./vendorimport/vendorimport.module').then(m => m.VendorimportModule), canActivate: [MsalGuard] },
  { path: 'partnerimport', loadChildren: () => import('./partnerimport/partnerimport.module').then(m => m.PartnerimportModule), canActivate: [MsalGuard] },
  { path: 'referralimport', loadChildren: () => import('./referralimport/referralimport.module').then(m => m.ReferralimportModule), canActivate: [MsalGuard] },
  { path: 'dealsbystatus', loadChildren: () => import('./dealsbystatus/dealsbystatus.module').then(m => m.DealsbystatusModule), canActivate: [MsalGuard] },
  { path: 'chart', loadChildren: () => import('./chart/chart.module').then(m => m.ChartModule), canActivate: [MsalGuard] },
  { path: 'emailtemplate', loadChildren: () => import('./emailtemplate/emailtemplate.module').then(m => m.EmailtemplateModule), canActivate: [MsalGuard] },
  { path: 'editemailtemplate', loadChildren: () => import('./emailtemplate/emailtemplate.module').then(m => m.EmailtemplateModule), canActivate: [MsalGuard] },
  { path: 'opportunityrevenuereport', loadChildren: () => import('./opportunityrevenuereport/opportunityrevenuereport.module').then(m => m.OpportunityrevenuereportModule), canActivate: [MsalGuard] },
  { path: 'opportunitycostreport', loadChildren: () => import('./opportunitycostreport/opportunitycostreport.module').then(m => m.OpportunitycostreportModule), canActivate: [MsalGuard] },
  { path: 'opportunityclosingreport', loadChildren: () => import('./opportunityclosingreport/opportunityclosingreport.module').then(m => m.OpportunityclosingreportModule), canActivate: [MsalGuard] },
  { path: 'opportunitycostandcustomerreport', loadChildren: () => import('./opportunitycostandcustomerreport/opportunitycostandcustomerreport.module').then(m => m.OpportunitycostandcustomerreportModule), canActivate: [MsalGuard] },
  { path: 'opportunitydateprobability', loadChildren: () => import('./opportunitydateprobability/opportunitydateprobability.module').then(m => m.OpportunitydateprobabilityModule), canActivate: [MsalGuard] },
  { path: 'opportunityactualexpectedrevenue', loadChildren: () => import('./opportunityactualexpectedrevenue/opportunityactualexpectedrevenue.module').then(m => m.OpportunityactualexpectedrevenueModule), canActivate: [MsalGuard] },
  { path: 'opportunityvariancereport', loadChildren: () => import('./opportunityvariancereport/opportunityvariancereport.module').then(m => m.OpportunityvariancereportModule), canActivate: [MsalGuard] },
  { path: 'emaildashboard', loadChildren: () => import('./emaildashboard/emaildashboard.module').then(m => m.EmaildashboardModule), canActivate: [MsalGuard] },
  { path: 'usercharts', loadChildren: () => import('./usercharts/usercharts.module').then(m => m.UserchartsModule), canActivate: [MsalGuard] },
  { path: 'importsettings', loadChildren: () => import('./importsettings/importsettings.module').then(m => m.ImportsettingsModule), canActivate: [MsalGuard] },
  { path: 'contactimport', loadChildren: () => import('./contactimport/contactimport.module').then(m => m.ContactimportModule), canActivate: [MsalGuard] },
  { path: 'vwcontactlist', loadChildren: () => import('./vwcontactlist/vwcontactlist.module').then(m => m.VwcontactlistModule), canActivate: [MsalGuard] },
  { path: 'dealsclosedbymonth', loadChildren: () => import('./dealsclosedbymonth/dealsclosedbymonth.module').then(m => m.DealsclosedbymonthModule), canActivate: [MsalGuard] },
  { path: 'dealsclosedbyquarter', loadChildren: () => import('./dealsclosedbyquarter/dealsclosedbyquarter.module').then(m => m.DealsclosedbyquarterModule), canActivate: [MsalGuard] },
  { path: 'funnelprogress', loadChildren: () => import('./funnelprogress/funnelprogress.module').then(m => m.FunnelprogressModule), canActivate: [MsalGuard] },
  { path: 'winlossbyrep', loadChildren: () => import('./winlossbyrep/winlossbyrep.module').then(m => m.WinlossbyrepModule), canActivate: [MsalGuard] },
  { path: 'wondealsbyrep', loadChildren: () => import('./wondealsbyrep/wondealsbyrep.module').then(m => m.WondealsbyrepModule), canActivate: [MsalGuard] },
  { path: 'dealslostbyreason', loadChildren: () => import('./dealslostbyreason/dealslostbyreason.module').then(m => m.DealslostbyreasonModule), canActivate: [MsalGuard] },
  { path: 'revenueforecostbyrep', loadChildren: () => import('./revenueforecostbyrep/revenueforecostbyrep.module').then(m => m.RevenueforecostbyrepModule), canActivate: [MsalGuard] },
  { path: 'leadconversion', loadChildren: () => import('./leadconversion/leadconversion.module').then(m => m.LeadconversionModule), canActivate: [MsalGuard] },
  { path: 'opportunitieswonovertime', loadChildren: () => import('./opportunitieswonovertime/opportunitieswonovertime.module').then(m => m.OpportunitieswonovertimeModule), canActivate: [MsalGuard] },
  { path: 'opportunitieslostbyreason', loadChildren: () => import('./opportunitieslostbyreason/opportunitieslostbyreason.module').then(m => m.OpportunitieslostbyreasonModule), canActivate: [MsalGuard] },
  { path: 'proposalsclosedbycustomer', loadChildren: () => import('./proposalsclosedbycustomer/proposalsclosedbycustomer.module').then(m => m.ProposalsclosedbycustomerModule), canActivate: [MsalGuard] },
  { path: 'proposalsclosedbyrep', loadChildren: () => import('./proposalsclosedbyrep/proposalsclosedbyrep.module').then(m => m.ProposalsclosedbyrepModule) },
  { path: 'contactgroup', loadChildren: () => import('./contactgroup/contactgroup.module').then(m => m.ContactgroupModule), canActivate: [MsalGuard] },
  { path: 'reportsettings', loadChildren: () => import('./report-settings/report-settings.module').then(m => m.ReportSettingsModule), canActivate: [MsalGuard] },
  { path: 'officemailbox', loadChildren: () => import('./office-mailbox/office-mailbox.module').then(m => m.OfficeMailboxModule), canActivate: [MsalGuard] },
  { path: 'listDashboardConfig', loadChildren: () => import('./list-dashboard-config/list-dashboard-config.module').then(m => m.ListDashboardConfigModule), canActivate: [MsalGuard] },
  { path: 'listservices', loadChildren: () => import('./listservices/listservices.module').then(m => m.ListservicesModule), canActivate: [MsalGuard] },
  { path: 'addservice', loadChildren: () => import('./addservice/addservice.module').then(m => m.AddserviceModule), canActivate: [MsalGuard] },
  { path: 'editservice', loadChildren: () => import('./addservice/addservice.module').then(m => m.AddserviceModule), canActivate: [MsalGuard] },
  { path: 'addservicemodal', loadChildren: () => import('./addservice/addservice.module').then(m => m.AddserviceModule), canActivate: [MsalGuard], outlet: "modal" },
  { path: 'servicessteps', loadChildren: () => import('./servicessteps/servicessteps.module').then(m => m.ServicesstepsModule), canActivate: [MsalGuard] },
  { path: 'forgot', loadChildren: () => import('./forgot/forgot.module').then(m => m.ForgotModule) },
  { path: 'reset', loadChildren: () => import('./reset/reset.module').then(m => m.ResetModule) },
  { path: 'listevent', loadChildren: () => import('./listevent/listevent.module').then(m => m.ListeventModule), canActivate: [MsalGuard] },
  { path: 'addevent', loadChildren: () => import('./addevent/addevent.module').then(m => m.AddeventModule), canActivate: [MsalGuard] },
  { path: 'addeventmodal', loadChildren: () => import('./addevent/addevent.module').then(m => m.AddeventModule), canActivate: [MsalGuard], outlet: "modal" },
  { path: 'eventsteps', loadChildren: () => import('./eventsteps/eventsteps.module').then(m => m.EventstepsModule), canActivate: [MsalGuard] },
  { path: 'translater', loadChildren: () => import('./translater/translater.module').then(m => m.TranslaterModule), canActivate: [MsalGuard] },
  { path: 'template', loadChildren: () => import('./template/template.module').then(m => m.TemplateModule), canActivate: [MsalGuard] },
  { path: 'listtemplate', loadChildren: () => import('./listtemplate/listtemplate.module').then(m => m.ListtemplateModule), canActivate: [MsalGuard] },
  { path: 'template-draft/:id', loadChildren: () => import('./template-dictation/template-dictation.module').then(m => m.TemplateDictationModule), canActivate: [MsalGuard] },
  { path: 'template-dictation', loadChildren: () => import('./template-dictation/template-dictation.module').then(m => m.TemplateDictationModule), canActivate: [MsalGuard] },
  { path: 'signpad', loadChildren: () => import('./signpad/signpad.module').then(m => m.SignpadModule), canActivate: [MsalGuard] },
  { path: 'search', loadChildren: () => import('./search/search.module').then(m => m.SearchModule), canActivate: [MsalGuard] },
  { path: 'newcalendar', loadChildren: () => import('./newcalendar/newcalendar.module').then(m => m.NewcalendarModule), canActivate: [MsalGuard] },
  { path: 'patientform/:code', loadChildren: () => import('./basicform/basicform.module').then(m => m.BasicformModule) },
  { path: 'signup', loadChildren: () => import('./signup/signup.module').then(m => m.SignupModule) },
  { path: '', loadChildren: () => import('./landingpage/landingpage.module').then(m => m.LandingpageModule) },
  { path: 'login', loadChildren: () => import('./landingpage/landingpage.module').then(m => m.LandingpageModule) },
  { path: 'addtemppatient', loadChildren: () => import('./addtemppatient/addtemppatient.module').then(m => m.AddtemppatientModule) },
  { path: 'basicformmedicalassociates', loadChildren: () => import('./basicformmedicalassociates/basicformmedicalassociates.module').then(m => m.BasicformmedicalassociatesModule) },
  { path: 'patientform-approved', loadChildren: () => import('./patientform-approved/patientform-approved.module').then(m => m.PatientformApprovedModule) }
  
  //,{ path: 'addproduct', loadChildren: () => import('./addproduct/addproduct.module').then(m => m.AddproductModule) },
  //{ path: 'listproduct', loadChildren: () => import('./listproduct/listproduct.module').then(m => m.ListproductModule) }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
