namespace HIN_API.Query
{
    public static class DBQuery
    {
        public const string CreateUser = @"INSERT INTO [dbo].[Users]([Email],[IsEmailConfirmed],[FirstName],[LastName],[UserName],[Password],[PhoneNumber],[IsPhoneNumberVerified],[AccessFailedCount],[IsLocked],[IsTwoFactorEnabled],[TwoFactorCode],[TwoFactorExpiryTime],[TwoFactorType],[RoleId],[IsActive],[LastLogin],[CellNumber],[Skills],[CostPerHour],[GroupId],[UserTheme],[EmployeeTypeId],[CountryId],[UpdatedOn],[UpdatedBy],[UpdatedById],[CreatedOn],[CreatedBy],[CreatedById],[Commission],[Address],[City],[State],[ZipCode],[StateId],[Country],[CityId],[IsSales],[IsAdmin],[AboutMe],[EmailSignature],[AdminPassword],[ImageURL],[GmailUserName],[GmailPassword],[BranchId],[Signature]) VALUES
           ('{0}',1,NULL,NULL,'{0}','dSW/v/o6gbT5bAI2T4pyJg==',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Admin',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Admin@123',NULL,NULL,NULL,NULL,NULL) SELECT CAST(SCOPE_IDENTITY() as int)";

        public const string GetTenantDetail = @"SELECT * FROM CompanyRegister WHERE CompanyPracticeCode = @Code";
        public const string GetValidatedCode = @"SELECT * FROM CompanyRegister WHERE CompanyPracticeCode = @Code";

        public const string InsertTempPatient = "INSERT INTO TempPatient (PatientName, Address, City, State, Zipcode, Age, Gender, DOB, HomePhone, CellPhone, MaritalStatus, EmailAddress, EmergencyContact, Telephone, Allergies, NKA, Hypertension, Liverdisease, Diabetes, InsulinDependent, Cancer, HeartDisease, KidneyDisease, ThyroidDisease, Type, OtherMedicalProblems, PastSurgeriesAndHospitalization, Medication, BloodTransfusion, Sedentary, MildExercise, RegularVigorius, DrinkAlcohol, ConvernedDrink, UseTobocco, StreetDrugs, StreetDrugNeedle, SexuallyActive, Contraception, LiveAlone, FrequentlyFalls, Colonoscopy, ColonoscopyData, FatherHealthProblem, FatherAge, MotherHealthPProblem, MotherAge, siblingHealthProblem, siblingAge, PatientPrintedName, Date, PatientSignature, NombreDelPaciente, Fecha, FirmaDelPaciente, PatientAttenSign, AttenDate, FirmaDelAtencion, AtencionDate, CreatedOn, UpdatedOn, CreatedBy, UpdatedBy, CreatedById, UpdatedById, IsPatientApproved, G, P, A, LMP, Mamogram, PapSmear, LastName, PacksPerDay, Years, YearsToQuit, ContraceptionData, BloodTransfusionData, DrinkAlcoholData, Asthma, MentalDisorder, AttentionAgree, AtencionAgree, IsConsentEn, IsCONSENTIMIENTO) VALUES (@patientName, @address, @city, @state, @zipcode, @age, @gender, @dOB, @homePhone, @cellPhone, @maritalStatus, @emailAddress, @emergencyContact, @telephone, @allergies, @nKA, @hypertension, @liverdisease, @diabetes, @insulinDependent, @cancer, @heartDisease, @kidneyDisease, @thyroidDisease, @type, @otherMedicalProblems, @pastSurgeriesAndHospitalization, @medication, @bloodTransfusion, @sedentary, @mildExercise, @regularVigorius, @drinkAlcohol, @convernedDrink, @useTobocco, @streetDrugs, @streetDrugNeedle, @sexuallyActive, @contraception, @liveAlone, @frequentlyFalls, @colonoscopy, @colonoscopyData, @fatherHealthProblem, @fatherAge, @motherHealthPProblem, @motherAge, @siblingHealthProblem, @siblingAge, @patientPrintedName, @date, @patientSignature, @nombreDelPaciente, @fecha, @firmaDelPaciente, @patientAttenSign, @attenDate, @firmaDelAtencion, @atencionDate, @createdOn, @updatedOn, @createdBy, @updatedBy, @createdById, @updatedById, @isPatientApproved, @g, @p, @a, @lMP, @mamogram, @papSmear, @lastName, @packsPerDay, @years, @yearsToQuit, @contraceptionData, @bloodTransfusionData, @drinkAlcoholData, @asthma, @mentalDisorder, @attentionAgree, @atencionAgree, @isConsentEn, @isCONSENTIMIENTO)";

        public const string UpdateTempPatient = "UPDATE TempPatient SET Id = @id, PatientName = @patientName, Address = @address, City = @city, State = @state, Zipcode = @zipcode, Age = @age, Gender = @gender, DOB = @dOB, HomePhone = @homePhone, CellPhone = @cellPhone, MaritalStatus = @maritalStatus, EmailAddress = @emailAddress, EmergencyContact = @emergencyContact, Telephone = @telephone, Allergies = @allergies, NKA = @nKA, Hypertension = @hypertension, Liverdisease = @liverdisease, Diabetes = @diabetes, InsulinDependent = @insulinDependent, Cancer = @cancer, HeartDisease = @heartDisease, KidneyDisease = @kidneyDisease, ThyroidDisease = @thyroidDisease, Type = @type, OtherMedicalProblems = @otherMedicalProblems, PastSurgeriesAndHospitalization = @pastSurgeriesAndHospitalization, Medication = @medication, BloodTransfusion = @bloodTransfusion, Sedentary = @sedentary, MildExercise = @mildExercise, RegularVigorius = @regularVigorius, DrinkAlcohol = @drinkAlcohol, ConvernedDrink = @convernedDrink, UseTobocco = @useTobocco, StreetDrugs = @streetDrugs, StreetDrugNeedle = @streetDrugNeedle, SexuallyActive = @sexuallyActive, Contraception = @contraception, LiveAlone = @liveAlone, FrequentlyFalls = @frequentlyFalls, Colonoscopy = @colonoscopy, ColonoscopyData = @colonoscopyData, FatherHealthProblem = @fatherHealthProblem, FatherAge = @fatherAge, MotherHealthPProblem = @motherHealthPProblem, MotherAge = @motherAge, siblingHealthProblem = @siblingHealthProblem, siblingAge = @siblingAge, PatientPrintedName = @patientPrintedName, Date = @date, PatientSignature = @patientSignature, NombreDelPaciente = @nombreDelPaciente, Fecha = @fecha, FirmaDelPaciente = @firmaDelPaciente, PatientAttenSign = @patientAttenSign, AttenDate = @attenDate, FirmaDelAtencion = @firmaDelAtencion, AtencionDate = @atencionDate, CreatedOn = @createdOn, UpdatedOn = @updatedOn, CreatedBy = @createdBy, UpdatedBy = @updatedBy, CreatedById = @createdById, UpdatedById = @updatedById, IsPatientApproved = @isPatientApproved, G = @g, P = @p, A = @a, LMP = @lMP, Mamogram = @mamogram, PapSmear = @papSmear, LastName = @lastName, PacksPerDay = @packsPerDay, Years = @years, YearsToQuit = @yearsToQuit, ContraceptionData = @contraceptionData, BloodTransfusionData = @bloodTransfusionData, DrinkAlcoholData = @drinkAlcoholData, Asthma = @asthma, MentalDisorder = @mentalDisorder, AttentionAgree = @attentionAgree, AtencionAgree = @atencionAgree, IsConsentEn = @isConsentEn, IsCONSENTIMIENTO = @isCONSENTIMIENTO WHERE Id = @id";
    }
}
