export class Deal {
  public DealId: number;
  public OrganizationName: string;
  public Title: string;
  public Value: string;
  public PipelineGroupId: number;
  public PipelineId: number;
  public ExpectedCloseDate: Date;
  public Owner: number;
  public VisibleTo: string;
  public Phone: number;
  public Email: string;
  public UpdatedOn: Date;
  public UpdatedBy: string;
  public UpdatedById: number;
  public CreatedOn: Date;
  public CreatedBy: string;
  public CreatedById: number;
  public ContactId: number;
  public LeadId: number;
  public OrganizationId: number;
  public CurrencyId: number;
  public StatusId: number;
  public DealName: string;
  public Percentage: string;
  public Color: string;
  public NextStepDate: Date;
  public EstimationDate: Date;
  public LeadProvider: string;
  public LeadCost: string;
  public ExpectedRevenue: string;
  public Address: string;
  public City: string;
  public State: string;
  public Country: string;
  public ZipCode: string;
  public Website: string;
  public CompanyName: string;
  public TradeShowName: string;
  public TradeShowDate: Date;
  public OriginsWebsite: string;
  public OriginsLinkedIn: string;
  public IsFromExistingCustomer: boolean;
  public IsFromExistingLead: boolean;
  public NoOfEmployee: string;
  public AnnualRevenue: string;
  public Industry: string;
  public AssignedTo: number;
  public AssignedName: string;
  public AssignedType: string;
  public Application: string;
  public KeyFeatures: string;
  public PriceExpectation: number;
  public TimeFrame: string;
  public Evaluated: string;
  public Deployment: string;
  public Shopping: string;
  public EventId: number;
  public CancelReason: string;
  public DealNumber: string;
  public SecurityGroupId: number;
  public ActualAmount: number;
  public ReasonId: number;
  public OriginalPercentage: string;
  public StatusDate: Date;
  public OpportunityProviderId: number;
  public ProviderEvenShowId: number;
  public ProviderSocialMediaId: number;
  public ProviderInstagram: string;
  public ProviderFaceBook: string;
  public ProviderYoutube: string;
  public ProviderWeChat: string;
  public ProviderTwitter: string;
  public ProviderLikedIn: string;
  public ProviderSnapChat: string;
  public ProviderVendorId: number;
  public ProviderWebsite: string;
  public ProviderNetworkingId: number;
  public ProviderNetworkingContactId: number;
  public ProviderParterId: number;
  public ProviderReferralId: number;
  public ProviderLeadId: number;
  public ProviderInternalSalesId: number;
  public IsRecurrence: boolean;
  public ExpectedRevenuId: number;
  public ExpectedRevenuDuration: number;
  public ExpectedRevenuPerDuration: number;
  public Notes: string;
  public SortProperty: Date;
  public OppRequirements: string;
  public OppRequirementRemarks: string;
  public StartDate: Date;
  public EndDate: Date;
}
export class DealStatus {
  public Id: number;
  public Name: string;
}
export class DealReportsDto {
  public DealId: number;
  public DealName: string;
  public LeadName: string;
  public ExpectedRevenue: string;
  public DealStatus: string;
  public EstimationDate: Date;
  public DealPipeline: string;
  public LeadProvider: string;
  public CreatedOn: Date;
}
export class OpportunityCostDTO {
  public OpportunityName: string;
  public OpportunityStatus: number;
  public OpportunityStatusDate: string;
  public CreatedOn: string;
  public EstimationDate: string;
  public OriginalCost: string;
  public AdditionalLabourCost: number;
  public MaterialCost: number;
  public TotalCost: number
  public Percentage: string
  public SalesFunnel: string
  public ExpectedSales: string;
  public ActualAmount: string;
  public VarianceAmountDollar: number;
  public VarianceAmountPercentage: number;
  public ExpectedSalesCalculation: number;
  public ProbabilityVariance: number;

}
